In [1]:
#conda install pytorch torchvision torchaudio cpuonly -c pytorch

In [3]:
import torch

In [4]:
import numpy as np

In [5]:
data = [[20,10] , [3,4]]

In [6]:
x_data = torch.tensor(data)

In [7]:
x_data

tensor([[20, 10],
        [ 3,  4]])

In [8]:
a = torch.ones_like(x_data)
a

tensor([[1, 1],
        [1, 1]])

In [9]:
a = torch.zeros_like(x_data)
a

tensor([[0, 0],
        [0, 0]])

In [10]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand

tensor([[0.4243, 0.9857],
        [0.0378, 0.6797]])

In [11]:
shape = (5,4)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.7947, 0.6555, 0.8492, 0.9407],
        [0.3057, 0.0515, 0.8854, 0.1340],
        [0.9730, 0.3130, 0.8920, 0.5625],
        [0.5416, 0.9226, 0.7314, 0.4132],
        [0.1837, 0.8360, 0.3733, 0.1995]])

In [12]:
rand_ones = torch.ones(shape)
rand_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
rand_zeros = torch.zeros(shape)
rand_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
shape = (2,3,5)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[[0.7415, 0.1584, 0.8927, 0.4842, 0.6583],
         [0.2661, 0.9514, 0.0792, 0.0994, 0.2550],
         [0.8054, 0.0167, 0.0314, 0.6190, 0.2821]],

        [[0.3246, 0.1980, 0.9974, 0.6675, 0.5904],
         [0.5415, 0.9712, 0.9811, 0.5450, 0.7578],
         [0.3662, 0.1975, 0.0427, 0.4302, 0.5771]]])

In [15]:
print(rand_tensor.shape)

torch.Size([2, 3, 5])


In [16]:
print(rand_tensor.dtype)

torch.float32


In [17]:
print(rand_tensor.device)

cpu


In [18]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [24]:
#indexing
tensor = torch.rand(4,4)
tensor

tensor([[0.2292, 0.0765, 0.1400, 0.4165],
        [0.5186, 0.5902, 0.3773, 0.7240],
        [0.4839, 0.5103, 0.3289, 0.0166],
        [0.3913, 0.8387, 0.6172, 0.6602]])

In [25]:
#print first row 
print(tensor[0])

tensor([0.2292, 0.0765, 0.1400, 0.4165])


In [26]:
#print first column 
print(tensor[:,0])

tensor([0.2292, 0.5186, 0.4839, 0.3913])


In [27]:
#print last column 
print(tensor[:,-1])

tensor([0.4165, 0.7240, 0.0166, 0.6602])


In [28]:
#matrix multiplication

In [29]:
tensor

tensor([[0.2292, 0.0765, 0.1400, 0.4165],
        [0.5186, 0.5902, 0.3773, 0.7240],
        [0.4839, 0.5103, 0.3289, 0.0166],
        [0.3913, 0.8387, 0.6172, 0.6602]])

In [30]:
tensor.shape

torch.Size([4, 4])

In [31]:
y1 = tensor @ tensor.T
y1

tensor([[0.2515, 0.5185, 0.2029, 0.5153],
        [0.5185, 1.2839, 0.6882, 1.4089],
        [0.2029, 0.6882, 0.6030, 0.8313],
        [0.5153, 1.4089, 0.8313, 1.6733]])

In [32]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[0.2515, 0.5185, 0.2029, 0.5153],
        [0.5185, 1.2839, 0.6882, 1.4089],
        [0.2029, 0.6882, 0.6030, 0.8313],
        [0.5153, 1.4089, 0.8313, 1.6733]])

In [33]:
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)
y3

tensor([[0.2515, 0.5185, 0.2029, 0.5153],
        [0.5185, 1.2839, 0.6882, 1.4089],
        [0.2029, 0.6882, 0.6030, 0.8313],
        [0.5153, 1.4089, 0.8313, 1.6733]])

In [34]:
#aggregations

In [35]:
tensor

tensor([[0.2292, 0.0765, 0.1400, 0.4165],
        [0.5186, 0.5902, 0.3773, 0.7240],
        [0.4839, 0.5103, 0.3289, 0.0166],
        [0.3913, 0.8387, 0.6172, 0.6602]])

In [37]:
agg = tensor.sum()
print(agg)

tensor(6.9196)


In [39]:
agg.dtype

torch.float32

In [40]:
a = agg.item()
print(a)

6.919607162475586


In [41]:
print(type(a))

<class 'float'>


In [43]:
tensor

tensor([[0.2292, 0.0765, 0.1400, 0.4165],
        [0.5186, 0.5902, 0.3773, 0.7240],
        [0.4839, 0.5103, 0.3289, 0.0166],
        [0.3913, 0.8387, 0.6172, 0.6602]])

In [44]:
tensor.add_(2)
print(tensor)

tensor([[2.2292, 2.0765, 2.1400, 2.4165],
        [2.5186, 2.5902, 2.3773, 2.7240],
        [2.4839, 2.5103, 2.3289, 2.0166],
        [2.3913, 2.8387, 2.6172, 2.6602]])
